import { vi, type Mocked, type MockedFunction } from 'vitest'
import * as LSP from 'vscode-languageserver/node'

export function getMockConnection(): Mocked<LSP.Connection> {
  const console: any = {
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
    log: vi.fn(),
  }

  return {
    client: {
      connection: {} as any,
      register: vi.fn(),
      initialize: vi.fn(),
      fillServerCapabilities: vi.fn(),
    },
    console,
    dispose: vi.fn(),
    languages: {} as any,
    listen: vi.fn(),
    notebooks: {} as any,
    onCodeAction: vi.fn(),
    onCodeActionResolve: vi.fn(),
    onCodeLens: vi.fn(),
    onCodeLensResolve: vi.fn(),
    onColorPresentation: vi.fn(),
    onCompletion: vi.fn(),
    onCompletionResolve: vi.fn(),
    onDeclaration: vi.fn(),
    onDefinition: vi.fn(),
    onDidChangeConfiguration: vi.fn(),
    onDidChangeTextDocument: vi.fn(),
    onDidChangeWatchedFiles: vi.fn(),
    onDidCloseTextDocument: vi.fn(),
    onDidOpenTextDocument: vi.fn(),
    onDidSaveTextDocument: vi.fn(),
    onDocumentColor: vi.fn(),
    onDocumentFormatting: vi.fn(),
    onDocumentHighlight: vi.fn(),
    onDocumentLinkResolve: vi.fn(),
    onDocumentLinks: vi.fn(),
    onDocumentOnTypeFormatting: vi.fn(),
    onDocumentRangeFormatting: vi.fn(),
    onDocumentRangesFormatting: vi.fn(),
    onDocumentSymbol: vi.fn(),
    onExecuteCommand: vi.fn(),
    onExit: vi.fn(),
    onFoldingRanges: vi.fn(),
    onHover: vi.fn(),
    onImplementation: vi.fn(),
    onInitialize: vi.fn(),
    onInitialized: vi.fn(),
    onNotification: vi.fn() as MockedFunction<LSP.Connection['onNotification']>,
    onPrepareRename: vi.fn(),
    onProgress: vi.fn(),
    onReferences: vi.fn(),
    onRenameRequest: vi.fn(),
    onRequest: vi.fn() as MockedFunction<LSP.Connection['onRequest']>,
    onSelectionRanges: vi.fn(),
    onShutdown: vi.fn(),
    onSignatureHelp: vi.fn(),
    onTypeDefinition: vi.fn(),
    onWillSaveTextDocument: vi.fn(),
    onWillSaveTextDocumentWaitUntil: vi.fn(),
    onWorkspaceSymbol: vi.fn(),
    onWorkspaceSymbolResolve: vi.fn(),
    sendDiagnostics: vi.fn(),
    sendNotification: vi.fn() as MockedFunction<LSP.Connection['sendNotification']>,
    sendProgress: vi.fn(),
    sendRequest: vi.fn() as MockedFunction<LSP.Connection['sendRequest']>,
    telemetry: {} as any,
    tracer: {} as any,
    window: {
      attachWorkDoneProgress: vi.fn(),
      connection: {} as any,
      createWorkDoneProgress: vi.fn(),
      fillServerCapabilities: vi.fn(),
      initialize: vi.fn(),
      showDocument: vi.fn(),
      showErrorMessage: vi.fn(),
      showInformationMessage: vi.fn(),
      showWarningMessage: vi.fn(),
    },
    workspace: {
      textDocumentContent: {
        refresh: vi.fn(),
        on: vi.fn(),
      },
      applyEdit: vi.fn(),
      connection: {} as any,
      fillServerCapabilities: vi.fn(),
      getConfiguration: vi.fn(),
      getWorkspaceFolders: vi.fn(),
      initialize: vi.fn(),
      onDidChangeWorkspaceFolders: vi.fn(),
      onDidCreateFiles: vi.fn(),
      onDidDeleteFiles: vi.fn(),
      onDidRenameFiles: vi.fn(),
      onWillCreateFiles: vi.fn(),
      onWillDeleteFiles: vi.fn(),
      onWillRenameFiles: vi.fn(),
    },
  }
}
